# Generated by Django 4.1 on 2023-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField()),
                ('is_first_login', models.BooleanField(default=False)),
                ('md_code', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('max_user', models.IntegerField()),
                ('count_user', models.IntegerField()),
                ('create_by_id', models.BigIntegerField()),
            ],
        ),
    ]
